// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:87287dc0-7b3d-48de-9042-1869a4d92710",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_nf1Esx0Hx",
    "aws_user_pools_web_client_id": "2hhl4r03mtac8gciv07257umgd",
    "oauth": {},
    "aws_user_files_s3_bucket": "massive-load233138-hsgenv",
    "aws_user_files_s3_bucket_region": "us-east-1"
};

export default awsmobile;
